name: Proton Valve xbe nopackage Ubuntu CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2
      - name: Compile
        run: |
          sudo dpkg --add-architecture i386
          sudo apt update
          sudo apt install build-essential
          chown user -R ..
          chown user -R /tmp
          export CARGO_HOME="$PWD"
          rustup target add i686-unknown-linux-gnu
          cd proton-tkg
          sed -i 's/distro=""/distro="debuntu"/' proton-tkg.cfg
          sed -i 's/uninstaller="false"/uninstaller="true"/' proton-tkg.cfg
          sed -i 's/autoinstall="false"/autoinstall="true"/' proton-tkg.cfg
          sed -i 's/build_gstreamer="false"/build_gstreamer="true"/' proton-tkg.cfg
          sed -i 's/lib32_gstreamer="false"/lib32_gstreamer="true"/' proton-tkg.cfg
          touch tarplz
          yes|./proton-tkg.sh
      - name: Archive the artifacts
        uses: actions/upload-artifact@v2
        with:
          name: proton-tkg-build
          path: proton-tkg/built/*.tar
